---
namespace: staging
replicas:
  - name: nginx-deployment
    count: 1
images:
  - name: 386082652299.dkr.ecr.us-east-1.amazonaws.com/argocd
    newTag: 1.0
resources:
  - ../../app-base
# patches:
#   - target:
#       kind: Deployment
#     patch: |-
#       - op: add
#         path: /spec/template/spec/imagePullSecrets
#         value: [{ name: dockerconfigjson }]